### PR TITLE
Added newline in the pest file for parsing sgf with newlines.

### PR DESCRIPTION
**Pull request by SamBlaise**

### CODE REVIEW

**Comment by SamBlaise** [comment]
Are you still maintaining your lib because I found it pretty idiomatic, but it lacks some sgf tokens.
In this PR I added just the capacity of parsing SGF with newlines. I'll wait for your feedback in this PR.

**Comment by mipli** [comment]
Sorry about the lack of response here. Great to hear that you like how it works, was trying to make it as idiomatic as possible when creating it.

I'll take a look at what you've done tomorrow, and get back to you about it then.

**Comment by SamBlaise** [comment]
the last 2 commits of which may be in surplus because I changed the code a little bit and it was only the first 2 commits and the rest is missing. Anyway, I'm glad to have you back.

**Comment by mipli** [comment]
Nice job noticing that we don't actually skip the `I` coordinate when reading SGF files. Was so used to that coordinate being skipped on go boards that I just assumed it was the same for SGF files.

I'm not too fond of having `coordinate_or_pass` as an `Option<(u8, u8)>`. Think I would rather introduce a new enum for the to options:
```rust
enum Action {
    Move(u8, u8),
    Pass,
}
```
and then change the `SgfToken` to
```rust
   Move { color: Color, action: Action}
```

I think that makes it a bit clearer what the two token variants represents. Feels like there should be a better name than `Action` for the enum though, but can't think of what.

**Comment by SamBlaise** [comment]
I think it's perfect, I'll work on it. I allowed myself to notice that the library does not manage the tag "RE".

**Comment by mipli** [comment]
I've merged this PR, and released a new version on crates.io as well with the updates.

**Comment by mipli** [comment]
And thanks a lot for getting these things done @SamBlaise!

**Pull request merged**
